In [2]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([1, 2, 3], dtype=float)
print(b)

[1. 2. 3.]


In [4]:
c = np.arange(1,11)
print(c)
d = np.arange(1, 11, 2)
print(d)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [5]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [6]:
# array of ones/ array of zeros

np.ones((3,4))
#np.zeros((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.random.random((3,4)) 
# it creates array values of 3*4 with values bw 0 and 1

array([[0.15114199, 0.29922068, 0.2869529 , 0.01774093],
       [0.30585535, 0.81937395, 0.40474963, 0.11808915],
       [0.97505814, 0.53932392, 0.72352291, 0.69214312]])

In [8]:
# np.linspace(lower_range, upper_range, number_of_items)
np.linspace(-10, 10, 10)

# it generates all the ppints in equal distance(linear seperable points)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [9]:
#creating an identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

NUMPY ATTRIBUTES 

In [10]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2) #3d matrix

In [11]:
# ndim (shows the dimension of the array)

a3.ndim

3

In [12]:
# shape(it gives the number_of_arrays, rows, columns)

print(a3.shape)

(2, 2, 2)


In [13]:
# size (it gives the total items/size)
a2.size

12

In [14]:
# itemsize (returns size occupied by th items in bytes)

a1.itemsize

8

In [15]:
# dtype(returns the data type of items)

print(a1.dtype)

int64


CHANGING DATATYPE


In [16]:
#astype (changes the datatype)

a3.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

ARRAY OPERATIONS

In [17]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [18]:
#scalar operations

#arithmetic

# a1*2
a1 + 4

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
#relational

a2 > 15
#a2 == 14

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
# vector operations
#arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

ARRAY FUNCTIONS

In [21]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[87.,  5., 99.],
       [73., 33., 85.],
       [31.,  8., 15.]])

In [ ]:
# max/min/sum/prod

np.max(a1, axis=0)  # it gives max from every row
#np.sum(a1) gives the sum
#np.prod(a1) gives the product

array([87., 33., 99.])

In [ ]:
# mean/median/std/variance

np.mean(a1) #using axis we can find column wise or row wise mean

np.float64(48.44444444444444)

In [26]:
# trignometric_funcs

np.sin(a1)

array([[-0.82181784, -0.95892427, -0.99920683],
       [-0.67677196,  0.99991186, -0.17607562],
       [-0.40403765,  0.98935825,  0.65028784]])

In [29]:
# dot ptoduct

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12, 24).reshape(4,3)
answer = np.dot(a2,a3)
answer

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents

np.log(a1) #log value calculated

array([[4.46590812, 1.60943791, 4.59511985],
       [4.29045944, 3.49650756, 4.44265126],
       [3.4339872 , 2.07944154, 2.7080502 ]])

In [31]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[90., 80., 21.],
       [80., 82., 82.]])

INDEXING AND SLICING


In [32]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1[-1] #-ve index means start from last

np.int64(9)

In [34]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a2[1,2] #indexing according to 2d array

np.int64(6)

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5] # in slicing 5th index value is not included 

array([2, 3, 4])

ITERATING

In [40]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [41]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [42]:
for i in a3:
    print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [43]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


RESHAPING - TRANSPOSE/RAVEL

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(a2) #transposes the values

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [46]:
# ravel (it convert the array of any dimension to 1d array)

a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

STACKING -HSTACK / VSTACK


In [47]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
a6 = np.hstack((a4,a5))
a6

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [51]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

SPLITTING

In [ ]:
# HORIZONTAL SPLITTING
np.hsplit(a4,2)  #2 means how many parts u want to split

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [55]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]