In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.random.randint(1, 100, 15)
a

array([11, 61, 45,  7, 43, 32, 84, 90, 64, 98, 51, 16, 25, 55, 84],
      dtype=int32)

In [3]:
b = np.random.randint(1, 100, 24).reshape(6,4)
b

array([[41, 31, 75, 87],
       [81, 16, 84, 11],
       [22,  1, 80, 42],
       [55, 77,  6, 92],
       [59, 22, 56, 76],
       [94,  8, 66,  3]], dtype=int32)

np.sort

return a sorted array

In [4]:
np.sort(a)

array([ 7, 11, 16, 25, 32, 43, 45, 51, 55, 61, 64, 84, 84, 90, 98],
      dtype=int32)

In [7]:
np.sort(b, axis=0)

array([[22,  1,  6,  3],
       [41,  8, 56, 11],
       [55, 16, 66, 42],
       [59, 22, 75, 76],
       [81, 31, 80, 87],
       [94, 77, 84, 92]], dtype=int32)

In [8]:
# np.append() -- appends the value along the axis at the end of the array

np.append(a,200)

array([ 11,  61,  45,   7,  43,  32,  84,  90,  64,  98,  51,  16,  25,
        55,  84, 200])

In [9]:
b

array([[41, 31, 75, 87],
       [81, 16, 84, 11],
       [22,  1, 80, 42],
       [55, 77,  6, 92],
       [59, 22, 56, 76],
       [94,  8, 66,  3]], dtype=int32)

In [10]:
np.append(b, np.ones((b.shape[0],1)),axis=1)

array([[41., 31., 75., 87.,  1.],
       [81., 16., 84., 11.,  1.],
       [22.,  1., 80., 42.,  1.],
       [55., 77.,  6., 92.,  1.],
       [59., 22., 56., 76.,  1.],
       [94.,  8., 66.,  3.,  1.]])

In [12]:
#np.concatenate()-- concatenate a sequence of arrays along an existing axis

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2, 3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
#np.unique() -- it returns the unique values from the array



In [15]:
#np.expand_dims()-- we can get expanded dimensions of the array

a

array([11, 61, 45,  7, 43, 32, 84, 90, 64, 98, 51, 16, 25, 55, 84],
      dtype=int32)

In [17]:
np.expand_dims(a, axis=1)

array([[11],
       [61],
       [45],
       [ 7],
       [43],
       [32],
       [84],
       [90],
       [64],
       [98],
       [51],
       [16],
       [25],
       [55],
       [84]], dtype=int32)

In [ ]:
#np.where -- returns the indices of the element

np.where(a>50)  # it returns the indices of the elements who are greater than 50

(array([ 1,  6,  7,  8,  9, 10, 13, 14]),)

In [ ]:
np.where(a>50,0,a) #numbers greater than 50 are replaced by 0

array([11,  0, 45,  7, 43, 32,  0,  0,  0,  0,  0, 16, 25,  0,  0],
      dtype=int32)

In [ ]:
# np.argmax() -- returns the indices of max element of the array in a particular axis
# same is the working of argmin

np.argmax(a)

np.int64(9)

In [22]:
# np.cumsum() -- used when we calculate the cumulative sum of array elements over a given axis

np.cumsum(a)

array([ 11,  72, 117, 124, 167, 199, 283, 373, 437, 535, 586, 602, 627,
       682, 766])

In [23]:
# np.percentile() -- used to compute the nth percentile of the given data along specified axis

np.percentile(a, 100)

np.float64(98.0)

In [24]:
# np.histogram() -- shows frequency of given data using grpahical representation

np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 1, 1, 2, 2, 2, 0, 2, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [ ]:
# np.corrcoef() --- returns pearson product-moment correlation coefficients



In [27]:
# np.isin() --- it searches multiple elements in a single time

items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([90], dtype=int32)

In [29]:
# np.delete() --- returns a new array with the deletion of sub-arrays along with the mentioned axis


np.delete(a,0)

array([61, 45,  7, 43, 32, 84, 90, 64, 98, 51, 16, 25, 55, 84],
      dtype=int32)

SET FUNCTIONS
